parameters:
  vmImage: ''
  project: ''
  platform: ''
  target: ''
  configuration: 'Release'

jobs:
- job: ${{ parameters.project }}
  displayName: ${{ parameters.project }}
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
    submodules: recursive
  - task: PowerShell@2
    displayName: Cake Build ${{ parameters.project }}
    inputs:
      filePath: 'build.ps1'
      arguments: '-ScriptArgs "-build-version=$(Build.BuildNumber)","-build-target=${{ parameters.target }}","-build-configuration=${{ parameters.configuration }}"'
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact ${{ parameters.project }}
    inputs:
      targetPath: 'MonoGame.Framework/bin/${{ parameters.project }}/${{ parameters.configuration }}/HollowGames.Framework.${{ parameters.platform }}.$(Build.BuildNumber).nupkg'
