trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  versionMonoGame: '3.7.1'
  versionRevision: $[counter(variables['versionMonoGame'], 0)]

name: $(versionMonoGame).$(versionRevision)

jobs:
- job:
  displayName: Build Windows
  steps:
  - task: PowerShell@2
    displayName: Build DesktopGL
    inputs:
      filePath: 'build.ps1'
      arguments: '-ScriptArgs "-build-version=$(versionMonoGame).$(versionRevision) -build-target=BuildDesktopGL"'
  - task: PowerShell@2
    displayName: Build WindowsDX
    inputs:
      filePath: 'build.ps1'
      arguments: '-ScriptArgs "-build-version=$(versionMonoGame).$(versionRevision) -build-target=BuildWindowsDX"'
  - task: PowerShell@2
    displayName: Build WindowsUniversal
    inputs:
      filePath: 'build.ps1'
      arguments: '-ScriptArgs "-build-version=$(versionMonoGame).$(versionRevision) -build-target=BuildUWP"'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'bin/DesktopGL/Release/*.nupkg'
