trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  versionMonoGame: '3.7.1'
  versionRevision: $[counter(variables['versionMonoGame'], 0)]

name: $(versionMonoGame).$(versionRevision)

stages:

- stage:
  displayName: Build Windows
  jobs:

  - job:
    displayName: Build DesktopGL
    steps:
    - task: PowerShell@2
      displayName: Cake Build DesktopGL
      inputs:
        filePath: 'build.ps1'
        arguments: '-ScriptArgs @("-build-version=$(Build.BuildNumber)", "-build-target=BuildDesktopGL")'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'MonoGame.Framework/bin/DesktopGL/Release/HollowGames.Framework.DesktopGL.$(Build.BuildNumber).nupkg'

  - job:
    displayName: Build WindowsDX
    steps:
    - task: PowerShell@2
      displayName: Cake Build WindowsDX
      inputs:
        filePath: 'build.ps1'
        arguments: '-ScriptArgs @("-build-version=$(Build.BuildNumber)", "-build-target=BuildWindowsDX")'

  - job:
    displayName: Build WindowsUniversal
    steps:
    - task: PowerShell@2
      displayName: Cake Build WindowsUniversal
      inputs:
        filePath: 'build.ps1'
        arguments: '-ScriptArgs @("-build-version=$(Build.BuildNumber)", "-build-target=BuildWindowsUWP")'
